import io
from datetime import datetime
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute total pages and draw professional running
    headers and footers with a 'Page X of Y' style.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Header (Only on page 2 and later) - minimalist earthy running header
        if self._pageNumber > 1:
            self.setFont("Times-Bold", 8)
            self.setFillColor(colors.HexColor("#6b6a65")) # Muted sand-charcoal
            self.drawString(54, 750, "CODELENS AUDIT REPORT")
            self.setFont("Times-Italic", 8)
            self.drawRightString(558, 750, datetime.now().strftime("%B %d, %Y"))
            self.setStrokeColor(colors.HexColor("#dfdeda")) # Soft sand line
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer (On all pages)
        self.setFont("Times-Roman", 8)
        self.setFillColor(colors.HexColor("#6b6a65"))
        self.drawString(54, 40, "Confidential — Generated by CodeLens Code Review Tool")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_text)
        
        self.setStrokeColor(colors.HexColor("#dfdeda"))
        self.setLineWidth(0.5)
        self.line(54, 52, 558, 52)
        
        self.restoreState()

class PDFGenerator:
    @staticmethod
    def generate_review_pdf(review: Dict[str, Any]) -> io.BytesIO:
        """
        Creates an exceptionally clean, editorial-quality PDF review document.
        """
        buffer = io.BytesIO()
        
        # Page margins
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        
        styles = getSampleStyleSheet()
        
        # --- SOPHISTICATED TYPOGRAPHY STYLES (Times-Serif headers, Helvetica body) ---
        
        # Document Title
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontName="Times-Bold",
            fontSize=24,
            leading=28,
            textColor=colors.HexColor("#1c1c1b"), # Rich warm charcoal
            alignment=0,
            spaceAfter=6
        )
        
        # Subtitle
        subtitle_style = ParagraphStyle(
            "DocSubTitle",
            parent=styles["Normal"],
            fontName="Times-Italic",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#6b6a65"),
            spaceAfter=20
        )
        
        # File Scanned Title Header (Heading 1)
        h1_style = ParagraphStyle(
            "FileHeader",
            parent=styles["Heading1"],
            fontName="Times-Bold",
            fontSize=15,
            leading=18,
            textColor=colors.HexColor("#1c1c1b"),
            spaceBefore=16,
            spaceAfter=6,
            keepWithNext=True
        )
        
        # Section Titles (Heading 2)
        h2_style = ParagraphStyle(
            "SectionHeader",
            parent=styles["Heading2"],
            fontName="Times-Bold",
            fontSize=11,
            leading=14,
            textColor=colors.HexColor("#292927"),
            spaceBefore=12,
            spaceAfter=6,
            keepWithNext=True
        )
        
        # Core Body Typography
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=colors.HexColor("#1c1c1b")
        )
        
        # Blockquote summary paragraph
        summary_style = ParagraphStyle(
            "FileSummary",
            parent=body_style,
            fontName="Times-Italic",
            fontSize=9.5,
            leading=13.5,
            textColor=colors.HexColor("#3b3b38")
        )
        
        # List items
        bullet_style = ParagraphStyle(
            "BulletStyle",
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )
        
        # Table Typography
        th_style = ParagraphStyle(
            "TableHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=10.5,
            textColor=colors.white
        )
        
        td_style = ParagraphStyle(
            "TableCell",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor("#1c1c1b")
        )
        
        # Earthy severity color pill text styles
        severity_high = ParagraphStyle(
            "HighSev",
            parent=td_style,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#cc4d4d") # Earthy terracotta
        )
        severity_med = ParagraphStyle(
            "MedSev",
            parent=td_style,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#d48e46") # Earthy warm sand-gold
        )
        severity_low = ParagraphStyle(
            "LowSev",
            parent=td_style,
            fontName="Helvetica-Bold",
            textColor=colors.HexColor("#5a8e7a") # Earthy sage green
        )

        story = []
        
        # --- TITLE SECTION ---
        story.append(Paragraph("CodeLens Code Review Audit", title_style))
        story.append(Paragraph(f"Repository: {review['repo_name']} | Generated: {datetime.now().strftime('%B %d, %Y %I:%M %p')}", subtitle_style))
        
        # --- REPO SUMMARY INFO BLOCK ---
        metadata_data = [
            [
                Paragraph("<b>Repository URL:</b>", td_style),
                Paragraph(review["repo_url"], td_style),
                Paragraph("<b>Overall Score:</b>", td_style),
                Paragraph(f"<b>{review['overall_score']}/100</b>", td_style)
            ],
            [
                Paragraph("<b>Files Reviewed:</b>", td_style),
                Paragraph(str(review["files_reviewed"]), td_style),
                Paragraph("<b>Audit Date:</b>", td_style),
                Paragraph(datetime.now().strftime("%B %d, %Y"), td_style)
            ]
        ]
        
        metadata_table = Table(metadata_data, colWidths=[110, 194, 100, 100])
        metadata_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#faf9f6")), # Claude soft cream bg
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#dfdeda")), # Earthy soft sand lines
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 8),
            ('RIGHTPADDING', (0,0), (-1,-1), 8),
        ]))
        
        story.append(metadata_table)
        story.append(Spacer(1, 20))
        
        # --- DETAILED FILE ANALYSIS ---
        files_data = review["review_data"].get("files", [])
        
        for idx, file_rev in enumerate(files_data):
            # Page break for subsequent files to keep sections clear
            if idx > 0:
                story.append(PageBreak())
                
            file_container = []
            
            # File title and score
            file_header_text = f"{file_rev.get('filename', 'Unknown')} — Score: {file_rev.get('overall_score', 100)}/100"
            file_container.append(Paragraph(file_header_text, h1_style))
            
            # Blockquote Summary callout box (terracotta left keyline, cream fill)
            summary_text = file_rev.get("summary", "No summary provided.")
            summary_p = Paragraph(f"<b>Summary:</b> {summary_text}", summary_style)
            
            summary_table = Table([[summary_p]], colWidths=[504])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#faf9f6")),
                ('LINEBEFORE', (0,0), (0,-1), 1.5, colors.HexColor("#d97736")), # Burnt terracotta accent bar
                ('TOPPADDING', (0,0), (-1,-1), 8),
                ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                ('LEFTPADDING', (0,0), (-1,-1), 12),
                ('RIGHTPADDING', (0,0), (-1,-1), 8),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#dfdeda")),
            ]))
            
            file_container.append(summary_table)
            file_container.append(Spacer(1, 10))
            
            # 1. BUGS, PERFORMANCE, & SECURITY TABLES
            categories = [
                ("bugs", "🐞 Bugs & Correctness Issues"),
                ("performance", "⚡ Performance Recommendations"),
                ("security", "🔒 Security Vulnerabilities")
            ]
            
            for key, section_title in categories:
                issues = file_rev.get(key, [])
                if issues:
                    file_container.append(Paragraph(section_title, h2_style))
                    
                    # Columns: Line, Severity, Issue, Fix
                    # Width split: Line=35, Severity=50, Issue=200, Fix=219
                    table_data = [[
                        Paragraph("Line", th_style),
                        Paragraph("Severity", th_style),
                        Paragraph("Issue", th_style),
                        Paragraph("Actionable Fix", th_style)
                    ]]
                    
                    for item in issues:
                        line_val = str(item.get("line")) if item.get("line") is not None and item.get("line") != "" else "N/A"
                        
                        sev = item.get("severity", "low").lower()
                        if sev == "high":
                            sev_p = Paragraph("High", severity_high)
                        elif sev == "medium":
                            sev_p = Paragraph("Medium", severity_med)
                        else:
                            sev_p = Paragraph("Low", severity_low)
                            
                        issue_p = Paragraph(item.get("issue", ""), td_style)
                        fix_p = Paragraph(item.get("fix", ""), td_style)
                        
                        table_data.append([
                            Paragraph(line_val, td_style),
                            sev_p,
                            issue_p,
                            fix_p
                        ])
                        
                    issue_table = Table(table_data, colWidths=[35, 50, 200, 219])
                    issue_table.setStyle(TableStyle([
                        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1c1c1b")), # Claude charcoal header
                        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                        ('VALIGN', (0,0), (-1,-1), 'TOP'),
                        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#dfdeda")),
                        ('TOPPADDING', (0,0), (-1,-1), 6),
                        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                        ('LEFTPADDING', (0,0), (-1,-1), 6),
                        ('RIGHTPADDING', (0,0), (-1,-1), 6),
                        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#fdfcfb")])
                    ]))
                    
                    file_container.append(issue_table)
                    file_container.append(Spacer(1, 10))
            
            # 2. BEST PRACTICES
            bp_issues = file_rev.get("best_practices", [])
            if bp_issues:
                file_container.append(Paragraph("💡 Best Practice Concerns", h2_style))
                
                table_data = [[
                    Paragraph("Severity", th_style),
                    Paragraph("Principle & Issue", th_style),
                    Paragraph("Standard & Recommendation", th_style)
                ]]
                
                for item in bp_issues:
                    sev = item.get("severity", "low").lower()
                    if sev == "high":
                        sev_p = Paragraph("High", severity_high)
                    elif sev == "medium":
                        sev_p = Paragraph("Medium", severity_med)
                    else:
                        sev_p = Paragraph("Low", severity_low)
                        
                    issue_p = Paragraph(item.get("issue", ""), td_style)
                    fix_p = Paragraph(item.get("fix", ""), td_style)
                    
                    table_data.append([
                        sev_p,
                        issue_p,
                        fix_p
                    ])
                    
                bp_table = Table(table_data, colWidths=[55, 220, 229])
                bp_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1c1c1b")),
                    ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                    ('VALIGN', (0,0), (-1,-1), 'TOP'),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#dfdeda")),
                    ('TOPPADDING', (0,0), (-1,-1), 6),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 6),
                    ('LEFTPADDING', (0,0), (-1,-1), 6),
                    ('RIGHTPADDING', (0,0), (-1,-1), 6),
                    ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#fdfcfb")])
                ]))
                file_container.append(bp_table)
                file_container.append(Spacer(1, 10))
                
            # 3. REFACTOR SUGGESTIONS
            refactor = file_rev.get("refactor_suggestions", [])
            if refactor:
                file_container.append(Paragraph("🛠️ Refactor & Optimization Opportunities", h2_style))
                for item in refactor:
                    bullet_text = f"• <b>Issue:</b> {item.get('issue', '')}<br/><b>Refactor:</b> {item.get('fix', '')}"
                    file_container.append(Paragraph(bullet_text, bullet_style))
                file_container.append(Spacer(1, 10))
                
            # 4. POSITIVE HIGHLIGHTS
            positives = file_rev.get("positive_highlights", [])
            if positives:
                file_container.append(Paragraph("✨ Positive Patterns Detected", h2_style))
                for item in positives:
                    bullet_text = f"• {item}"
                    file_container.append(Paragraph(bullet_text, bullet_style))
                file_container.append(Spacer(1, 10))
                
            story.extend(file_container)
            
        # Build Document
        doc.build(story, canvasmaker=NumberedCanvas)
        
        buffer.seek(0)
        return buffer
